apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: rolling-demo
  labels:
    app: myapp
    app.openshift.io/runtime: spring-boot    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: quay.io/naveenkendyala/sboot-hello:v2
        ports:
          - containerPort: 8080
  strategy:
    # Default type is also RollingUpdate
    type: RollingUpdate
