apiVersion: v1
kind: Service
metadata:
  name: myapp-green
  namespace: blue-green-demo
  labels:
    app: myapp
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: myapp
    type: green
  type: LoadBalancer
